---
flush_iptables: true
reset_restart_network: true

reset_restart_network_service_name: >-
  {% if ansible_os_family == "RedHat" -%}
  {%-
    if ansible_distribution_major_version | int >= 8
    or is_fedora_coreos or ansible_distribution == "Fedora" -%}
  NetworkManager
  {%- else -%}
  network
  {%- endif -%}
  {%- elif ansible_distribution == "Ubuntu" -%}
  systemd-networkd
  {%- elif ansible_os_family == "Debian" -%}
  networking
  {%- endif %}
