---
- name: Check if helm is installed
  shell: |
    {% raw %}
    helm version --template={{ "{{ .Version }}" }}
    {% endraw %}
  register: helm_installed
  changed_when: false
  failed_when: false

- name: Install Helm repository GPG key
  apt_key:
    url: "https://packages.buildkite.com/helm-linux/helm-debian/gpgkey"
    keyring: "/usr/share/keyrings/helm.gpg"
    state: present
  when: helm_installed.rc != 0

- name: Ensure apt-transport-https package is installed
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  when: helm_installed.rc != 0

- name: Add Helm APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    filename: "helm-stable-debian.list"
    state: present
  when: helm_installed.rc != 0

- name: Install Specific Helm Version
  apt:
    name: helm=3.17.4-1
    state: present
    update_cache: yes
  when: helm_installed.rc != 0
