---
- name: install | Copy kubeadm binary from download dir
  copy:
    src: "{{ local_release_dir }}/kubeadm-{{ kubeadm_version }}-{{ image_arch }}"
    dest: "{{ bin_dir }}/kubeadm"
    mode: 0755
    remote_src: true
  tags:
    - kubeadm
  when:
    - not inventory_hostname in groups['kube_control_plane']

- name: install | Copy kubelet binary from download dir
  copy:
    src: "{{ local_release_dir }}/kubelet-{{ kube_version }}-{{ image_arch }}"
    dest: "{{ bin_dir }}/kubelet"
    mode: 0755
    remote_src: true
  tags:
    - kubelet
    - upgrade
  notify: Node | restart kubelet
