---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Chmod reset file
  become: false
  file:
    path: "{{ home_dir_path.stdout }}/cp-deployment/standalone/reset-cp-cluster.sh"
    mode: "0755"

- name: Reset container platform
  become: false
  shell: |
    ssh {{ hostvars[inventory_hostname].ansible_host }} 'cd {{ home_dir_path.stdout }}/cp-deployment/standalone && ./reset-cp-cluster.sh' 2>&1 | tee /dev/tty
  delegate_to: localhost
