---
- name: APT upgrade
  when:
  - system_upgrade
  - ansible_os_family == "Debian"
  include_tasks: apt.yml
  tags:
  - system-upgrade-apt

- name: YUM upgrade
  when:
  - system_upgrade
  - ansible_os_family == "RedHat"
  - not is_fedora_coreos
  include_tasks: yum.yml
  tags:
  - system-upgrade-yum
