---
- hosts: cloudcore_node
  gather_facts: False
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: cp/edge/keadm_amd64 }

- hosts: edge_node
  gather_facts: True
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: cp/edge/keadm_amd64, when: ansible_architecture == "x86_64" }
    - { role: cp/edge/keadm_arm64, when: ansible_architecture == "aarch64" }

- hosts: cloudcore_node
  gather_facts: False
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: cp/edge/keadm_init }

- hosts: edge_node
  gather_facts: True
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: cp/edge/cri_install }
    - { role: cp/edge/keadm_join }

- hosts: cloudcore_node
  gather_facts: False
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: cp/edge/edgemesh }

- hosts: cloudcore_node
  gather_facts: False
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: cp/cve_cce/amd64 }

- hosts: edge_node
  gather_facts: True
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: cp/cve_cce/amd64, when: ansible_architecture == "x86_64" }
    - { role: cp/cve_cce/arm64, when: ansible_architecture == "aarch64" }
