---
- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    update_cache: yes

- name: Add iptalb prerouting
  shell: |
    iptables -t nat -I PREROUTING -d {{ istio_eastwest_private_ip }} -j DNAT --to-destination {{ istio_eastwest_public_ip }}
    netfilter-persistent save
    cat <<EOF > /etc/systemd/system/netfilter-persistent.service.d/iptables.conf
    [Unit]
    Conflicts=iptables.service ip6tables.service
    [Service]
    Restart=on-failure
    RestartSec=5s
    EOF
    systemctl daemon-reload
