---
- name: get home dir path
  become_user: ubuntu
  shell: "echo $HOME"
  register: home_dir_path

- name: cri-o download
  shell: |
    wget https://storage.googleapis.com/cri-o/artifacts/cri-o.arm64.c0b2474b80fd0844b883729bda88961bed7b472b.tar.gz
    tar zxvf cri-o.arm64.c0b2474b80fd0844b883729bda88961bed7b472b.tar.gz
    cd cri-o
    ./install

- name: enable crio.service
  shell: |
    sed -i 's/,metacopy=on//g' /etc/containers/storage.conf
    systemctl daemon-reload
    systemctl enable crio.service
    systemctl start crio.service
