- type: replace
  path: /instance_groups/-
  value:
    name: container-jenkins-broker
    instances: ((jenkins_broker_instances))
    networks:
    - name: ((service_private_networks_name))
    azs: ((jenkins_broker_azs))
    vm_type: ((vm_type_container_small_api))
    stemcell: ((stemcell_alias))
    update:
      max_in_flight: 1
      serial: true
    jobs:
    - name: container-jenkins-broker
      release: ((container_platform_release_name))
      properties:
        logging:
          path: classpath:logback-spring.xml
          file: logs/application.log
        jenkins:
          serviceDefinition:
            plan1:
              id: 1653cb80-0077-11ea-aaef-0800200c9a66
              name: jenkins_20GB
              desc: Installing Jenkins in Docker in a Container
              type: A
            bullet:
              desc: 100
              name: 100
            desc: Installing Jenkins in Docker in a Container 20GB
            name: container-jenkins-service
            id: 0ef99f90-0077-11ea-aaef-0800200c9a66
          namespace: ((jenkins_namespace))
          namespace_file_path: ((jenkins_namespace_file))
          secret_file_path: ((jenkins_secret_file))
        server:
          port: ((jenkins_broker_port))
        jpa:
          show_sql: true
          hibernate_ddl_auto: none
        datasource:
          username: ((mariadb_admin_user_id))
          password: ((mariadb_admin_user_password))
        caas:
          repository:
            port: ((private_image_repository_port))
          k8s_api_server_ip: ((k8s_api_server_ip))
          k8s_api_server_port: ((k8s_api_server_port))
          k8s_auth_bearer: ((k8s_auth_bearer))
