---
addusers:
  - name: etcd
    comment: "Etcd user"
    create_home: yes
    home: "{{ etcd_data_dir }}"
    system: yes
    shell: /sbin/nologin

  - name: kube
    comment: "Kubernetes user"
    create_home: no
    system: yes
    shell: /sbin/nologin
    group: "{{ kube_cert_group }}"
