---
addusers:
  - name: etcd
    comment: "Etcd user"
    create_home: true
    home: "{{ etcd_data_dir }}"
    system: true
    shell: /sbin/nologin

  - name: kube
    comment: "Kubernetes user"
    create_home: false
    system: true
    shell: /sbin/nologin
    group: "{{ kube_cert_group }}"
