---

- name: Create binary destination folder
  file:
    mode: '0755'
    state: directory
    path: "{{ crun_bin_dir }}"

- name: Check if binary exists
  stat:
    path: "{{ crun_bin_dir }}/crun"
  register: crun_stat

# TODO: use download_file.yml
- name: Download binary
  get_url:
    url: "{{ crun_release_url }}"
    dest: "{{ crun_bin_dir }}/crun"
    mode: '0755'
  when: not crun_stat.stat.exists
  environment: "{{ proxy_env }}"
