---
- name: Kubeadm | Create directory to store kubeadm patches
  file:
    path: "{{ kubeadm_patches_dir }}"
    state: directory
    mode: "0640"
  when: kubeadm_patches | length > 0

- name: Kubeadm | Copy kubeadm patches from inventory files
  copy:
    content: "{{ item.patch | to_yaml }}"
    dest: "{{ kubeadm_patches_dir }}/{{ item.target }}{{ suffix }}+{{ item.type | d('strategic') }}.yaml"
    owner: "root"
    mode: "0644"
  loop: "{{ kubeadm_patches }}"
  loop_control:
    index_var: suffix
