---
- name: cri-o download
  shell: |
    wget https://storage.googleapis.com/cri-o/artifacts/cri-o.arm64.d93b2dfb8d0f2ad0f8b9061d941e3b216baa5814.tar.gz
    tar zxvf cri-o.arm64.d93b2dfb8d0f2ad0f8b9061d941e3b216baa5814.tar.gz
    cd cri-o
    ./install
    rm -rf cri-o*

- name: enable crio.service
  shell: |
    echo unqualified-search-registries = [\"docker.io\", \"quay.io\"] > /etc/containers/registries.conf
    sed -i 's/,metacopy=on//g' /etc/containers/storage.conf
    systemctl daemon-reload
    systemctl enable crio.service
    systemctl start crio.service
