---
- name: Get home dir path
  become: false
  shell: "echo /home/ubuntu"
  register: home_dir_path

- name: Copy kube config file
  become: false
  shell: "cp {{ home_dir_path.stdout }}/.kube/config {{ home_dir_path.stdout }}/.kube/kubeconfig"

- name: Modify kube config file (api)
  become: false
  vars:
    idx: "{{ groups['kube_control_plane'].index(inventory_hostname) }}"
  replace:
    path: "{{ home_dir_path.stdout }}/.kube/kubeconfig"
    regexp: "server: https://127.0.0.1:6443"
    replace: "server: https://{{ master1_node_public_ip[idx|int] }}:6443"

- name: Modify kube config file (cluster)
  become: false
  replace:
    path: "{{ home_dir_path.stdout }}/.kube/kubeconfig"
    regexp: "kubernetes-admin@cluster.local"
    replace: "cluster{{ groups['kube_control_plane'].index(inventory_hostname)|int + 1|int }}"

- name: Modify kube config file (context)
  become: false
  replace:
    path: "{{ home_dir_path.stdout }}/.kube/kubeconfig"
    regexp: "cluster.local"
    replace: "cluster{{ groups['kube_control_plane'].index(inventory_hostname)|int + 1|int }}"

- name: Modify kube config file (user)
  become: false
  replace:
    path: "{{ home_dir_path.stdout }}/.kube/kubeconfig"
    regexp: "kubernetes-admin"
    replace: "cluster{{ groups['kube_control_plane'].index(inventory_hostname)|int + 1|int }}-admin"

- name: Copy kube config file
  become: false
  fetch:
    src: "{{ home_dir_path.stdout }}/.kube/kubeconfig"
    dest: "{{ lookup('env', 'HOME') }}/.kube/config{{ groups['kube_control_plane'].index(inventory_hostname)|int + 1|int }}"
    flat: yes
