---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-clone
spec:
  storageClassName: rook-nfs
  dataSource:
    name: nfs-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
