---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Download kustomize
  shell: |
    wget https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Copy kustomize Bin File
  copy:
    src: "{{ home_dir_path.stdout }}/kustomize_3.2.0_linux_amd64"
    dest: /usr/local/bin/kustomize
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Delete kustomize File
  file:
    path: "{{ home_dir_path.stdout }}/kustomize_3.2.0_linux_amd64"
    state: absent
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Deploy Kubeflow
  shell: |
    cd {{ home_dir_path.stdout }}/paas-ta-container-platform-deployment/standalone/applications/kubeflow-1.6.1
    while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
