---
- name: Install | Copy kubeadm binary from download dir
  copy:
    src: "{{ downloads.kubeadm.dest }}"
    dest: "{{ bin_dir }}/kubeadm"
    mode: 0755
    remote_src: true
  tags:
    - kubeadm
  when:
    - not inventory_hostname in groups['kube_control_plane']

- name: Install | Copy kubelet binary from download dir
  copy:
    src: "{{ downloads.kubelet.dest }}"
    dest: "{{ bin_dir }}/kubelet"
    mode: 0755
    remote_src: true
  tags:
    - kubelet
    - upgrade
  notify: Node | restart kubelet
