---

crio_storage_driver: "overlay"

crio_versioned_pkg:
  "1.24":
    - "cri-o-1.24.*"
  "1.23":
    - "cri-o-1.23.*"
  "1.22":
    - "cri-o-1.22.*"

default_crio_packages: "{{ crio_versioned_pkg[crio_version] }}"

crio_packages: "{{ centos_crio_packages | default(default_crio_packages) }}"
