#!/bin/bash

export MASTER_NODE_HOSTNAME=
export MASTER_NODE_PUBLIC_IP=
export MASTER_NODE_PRIVATE_IP=

export WORKER_NODE_CNT=

export WORKER1_NODE_HOSTNAME=
export WORKER1_NODE_PUBLIC_IP=
export WORKER1_NODE_PRIVATE_IP=

export CLUSTER_PRIVATE_KEY=
