---
crio_versioned_pkg:
  "1.19":
    - "cri-o-1.19.*"
  "1.18":
    - "cri-o-1.18.*"
  "1.17":
    - "cri-o-1.17.*"

default_crio_packages: "{{ crio_versioned_pkg[crio_version] }}"

crio_packages: "{{ centos_crio_packages | default(default_crio_packages) }}"
