---
- name: get home dir path
  become_user: ubuntu
  shell: "echo $HOME"
  register: home_dir_path

- name: cri-o install
  shell: "{{ home_dir_path.stdout }}/paas-ta-container-platform-deployment/edge/cri-o/install"

- name: enable crio.service
  shell: |
    sed -i 's/,metacopy=on//g' /etc/containers/storage.conf
    systemctl daemon-reload
    systemctl enable crio.service
    systemctl start crio.service
