#!/bin/bash

export CLOUDCORE_PRIVATE_VIP=
export CLOUDCORE_VIP=

export CLOUDCORE1_NODE_HOSTNAME=
export CLOUDCORE2_NODE_HOSTNAME=

export EDGE_HOSTS=

export EDGE1_NODE_HOSTNAME=
export EDGE1_NODE_PUBLIC_IP=
