---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Unset NHN Cloud environment variables and clear from cp-cluster-vars.sh
  no_log: true
  shell: |
    unset -v $(compgen -v | grep -E ^CLUSTER[0-9]_CSP_TYPE)
    unset -v $(compgen -v | grep -E ^CLUSTER[0-9]_NHN_USERNAME)
    unset -v $(compgen -v | grep -E ^CLUSTER[0-9]_NHN_PASSWORD)
    unset -v $(compgen -v | grep -E ^CLUSTER[0-9]_NHN_TENANT_ID)
    unset -v $(compgen -v | grep -E ^CLUSTER[0-9]_NHN_VIP_SUBNET_ID)

    sed -i -E "s/(CLUSTER[0-9]+_CSP_TYPE)=.*/\1=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh
    sed -i -E "s/(CLUSTER[0-9]+_NHN_USERNAME)=.*/\1=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh
    sed -i -E "s/(CLUSTER[0-9]+_NHN_PASSWORD)=.*/\1=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh
    sed -i -E "s/(CLUSTER[0-9]+_NHN_TENANT_ID)=.*/\1=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh
    sed -i -E "s/(CLUSTER[0-9]+_NHN_VIP_SUBNET_ID)=.*/\1=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh

  when:
    - lookup('env', 'CSP_TYPE') | trim == "NHN"
