---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Add filter labels to Kubernetes API services
  shell: |
    kubectl label services kubernetes service.edgemesh.kubeedge.io/service-proxy-name=""
    kubectl label services cloudcore -n kubeedge service.edgemesh.kubeedge.io/service-proxy-name=""

- name: apply edgemesh crds
  shell: "kubectl apply -f {{ home_dir_path.stdout }}/cp-deployment/edge/edgemesh/crds/istio"

- name: apply edgemesh server
  shell: "kubectl apply -f {{ home_dir_path.stdout }}/cp-deployment/edge/edgemesh/agent/"
