name: Build & Apply Katib manifests in KinD
on:
  pull_request:
    paths:
      - apps/katib/upstream/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install KinD
      run: ./tests/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config tests/gh-actions/kind-cluster-1-22.yaml

    - name: Install kustomize
      run: ./tests/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./tests/gh-actions/install_istio.sh

    - name: Install cert-manager
      run: ./tests/gh-actions/install_cert_manager.sh

    - name: Build & Apply manifests
      run: |
        cd apps/katib/upstream
        kubectl create ns kubeflow
        kustomize build installs/katib-with-kubeflow | kubectl apply -f -
# temporary remove the condition check that fails for mysql on GH Actions
#        kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout 180s

# temporary remove the katib experiment action until mysql condition check issue is resolved
#    - name: Create katib experiment
#      run: |
#        kubectl apply -f tests/gh-actions/katib_test.yaml
#        kubectl wait --for=condition=Succeeded trials.kubeflow.org -n kubeflow-user --all --timeout 300s
#        kubectl wait --for=condition=Succeeded experiments.kubeflow.org -n kubeflow-user --all --timeout 300s
