---
- name: Calculate etcd cert serial
  command: "openssl x509 -in {{ kube_cert_dir }}/apiserver-etcd-client.crt -noout -serial"
  register: "etcd_client_cert_serial_result"
  changed_when: false
  tags:
    - network

- name: Set etcd_client_cert_serial
  set_fact:
    etcd_client_cert_serial: "{{ etcd_client_cert_serial_result.stdout.split('=')[1] }}"
  tags:
    - network

- name: Ensure etcdctl script is installed
  import_role:
    name: etcdctl
  when: etcd_deployment_type == "kubeadm"

- name: Set ownership for etcd data directory
  file:
    path: "{{ etcd_data_dir }}"
    owner: "{{ etcd_owner }}"
    group: "{{ etcd_owner }}"
    mode: 0700
  when: etcd_deployment_type == "kubeadm"
