apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-server-cfg
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-server
data:
  edgemesh-server.yaml: |
    # For more detailed configuration, please refer to: https://edgemesh.netlify.app/reference/config-items.html#edgemesh-server
    modules:
      tunnel:
        enable: true
        # edgemesh-server will try to fetch advertise address by itself,
        # you also can specify the advertise address for edgemesh-server by advertiseAddress field.
        # advertiseAddress:
        # - 119.8.58.38
        # - 1.1.1.153
        # - 192.168.0.7
