---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Download kustomize
  shell: |
    wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.0/kustomize_v5.0.0_linux_amd64.tar.gz
    tar zxvf kustomize_v5.0.0_linux_amd64.tar.gz

- name: Copy kustomize Bin File
  copy:
    src: "{{ home_dir_path.stdout }}/kustomize"
    dest: /usr/local/bin/kustomize
    mode: 0755

- name: Delete Kustomize tar File
  file:
    path: "{{ home_dir_path.stdout }}/kustomize_v5.0.0_linux_amd64.tar.gz"
    state: absent

- name: Delete kustomize File
  file:
    path: "{{ home_dir_path.stdout }}/kustomize"
    state: absent

- name: Deploy Kubeflow
  shell: |
    cd {{ home_dir_path.stdout }}/cp-deployment/standalone/applications/kubeflow-1.7.0
    while ! kustomize build example | awk '!/well-defined/' | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done
