---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Copy vars file
  become: false
  copy:
    src: "{{ lookup('env', 'HOME') }}/cp-deployment/multi/cp-cluster-vars{{ groups['kube_control_plane'].index(inventory_hostname)|int + 1|int }}.sh"
    dest: "{{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars.sh"

- name: Copy vars file (cluster1)
  become: false
  copy:
    src: "{{ lookup('env', 'HOME') }}/cp-deployment/multi/cp-cluster-vars2.sh"
    dest: "{{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars-tmp.sh"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Copy vars file (cluster2)
  become: false
  copy:
    src: "{{ lookup('env', 'HOME') }}/cp-deployment/multi/cp-cluster-vars1.sh"
    dest: "{{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars-tmp.sh"
  when:
    - inventory_hostname == groups['kube_control_plane'][1]

- name: Copy key file
  become: false
  copy:
    src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    dest: "{{ home_dir_path.stdout }}/.ssh/id_rsa"

- name: Chmod key file
  become: false
  file:
    path: "{{ home_dir_path.stdout }}/.ssh/id_rsa"
    mode: "0600"
