---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: apply edgemesh crds
  shell: "kubectl apply -f {{ home_dir_path.stdout }}/paas-ta-container-platform-deployment/edge/edgemesh/crds/istio"

- name: apply edgemesh server
  shell: "kubectl apply -f {{ home_dir_path.stdout }}/paas-ta-container-platform-deployment/edge/edgemesh/gateway/"

- name: apply edgemesh server
  shell: "kubectl apply -f {{ home_dir_path.stdout }}/paas-ta-container-platform-deployment/edge/edgemesh/agent/"
