---
- name: Warn for usage of deprecated role
  fail:
    msg: kubespray-defaults is deprecated, switch to kubespray_defaults
  ignore_errors: true # noqa ignore-errors
  run_once: true

- name: Compat for direct role import
  import_role:
    name: kubespray_defaults
