---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: copy keadm token file
  copy:
    src: "{{ home_dir_path.stdout }}/keadm_token"
    dest: "{{ home_dir_path.stdout }}"

- name: get keadm token
  shell: "echo $(<{{ home_dir_path.stdout }}/keadm_token)"
  register: keadm_token
  args:
    executable: /bin/bash

- name: keadm join
  shell: "nohup keadm join --cgroupdriver systemd --cloudcore-ipport {{ cloudcore_vip }}:10000 --kubeedge-version 1.14.4 --remote-runtime-endpoint unix:///var/run/crio/crio.sock --token {{ keadm_token.stdout }} --with-mqtt=false"

- name: remove keadm token file
  file:
    path: "{{ home_dir_path.stdout }}/keadm_token"
    state: absent

- name: modify edgecore
  lineinfile:
    path: /etc/kubeedge/config/edgecore.yaml
    insertafter: "tailoredKubeletConfig:"
    line: "{{ item }}"
  with_items:
    - "        - 169.254.96.16"
    - "      clusterDNS:"
