---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Wait for kube-apiserver to be running
  shell: |
    echo $(kubectl get pods -n kube-system | grep kube-apiserver | awk 'NR==1 { print $3 }')
  register: kube_status
  until: kube_status.stdout == "Running"
  retries: 15
  delay: 10

- name: Wait for kyverno-admission-controller to be running
  shell: |
    echo $(kubectl get pods -n kyverno | grep kyverno-admission-controller | awk '{print $3}')
  register: kyverno_status
  until: kyverno_status.stdout == "Running"
  retries: 15
  delay: 10
  when:
    - lookup('env', 'INSTALL_KYVERNO') | trim == "Y"

- name: Create k-paas-system namespace
  shell: |
    kubectl create ns k-paas-system
  ignore_errors: yes

- name: Install openbao
  become: false
  shell: |
    mkdir -p {{ home_dir_path.stdout }}/charts
    helm pull -d {{ home_dir_path.stdout }}/charts "oci://registry.k-paas.org/kpaas/openbao" --version "0.12.0"
    helm install openbao {{ home_dir_path.stdout }}/charts/openbao-0.12.0.tgz -n k-paas-system -f - <<EOF
    {% raw %}
    injector:
      image:
        registry: "registry.k-paas.org"
        repository: "openbao/vault-k8s"
      agentImage:
        registry: "registry.k-paas.org"
        repository: "openbao/openbao"
      securityContext:
        pod:
          runAsUser: 1000
          fsGroup: 1000
        container:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: "RuntimeDefault"
      affinity: |
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "openbao.name" . }}-agent-injector
                  app.kubernetes.io/instance: "{{ .Release.Name }}"
                  component: webhook
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/edge
                    operator: DoesNotExist
    server:
      image:
        registry: "registry.k-paas.org"
        repository: "openbao/openbao"
      ingress:
        enabled: false
      dataStorage:
        storageClass: "cp-storageclass"
      statefulSet:
        securityContext:
          pod:
            runAsUser: 1000
            fsGroup: 1000
          container:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
      affinity: |
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "openbao.name" . }}
                  app.kubernetes.io/instance: "{{ .Release.Name }}"
                  component: server
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/edge
                    operator: DoesNotExist
    csi:
      daemonSet:
        securityContext:
          pod:
            runAsUser: 1000
            fsGroup: 1000
          container:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/edge
                      operator: DoesNotExist
    {% endraw %}
    EOF

- name: Wait for openbao to be running
  shell: kubectl get pods openbao-0 -n k-paas-system | grep Running | awk '{print $3}'
  register: openbao_status
  until: openbao_status.stdout == "Running"
  retries: 15
  delay: 10

- name: Set openbao URL
  set_fact:
    openbao_url: openbao.k-paas-system.svc.cluster.local:8200

- name: Initialize openbao
  no_log: true
  shell: |
    curl --silent --show-error -k -X POST -d '{"secret_shares": 3, "secret_threshold": 2}' {{ openbao_url }}/v1/sys/init
  register: init_result

- name: Save openbao keys to file
  no_log: true
  shell: |
    echo {{ init_result.stdout }} | sed "s/,root_token.*/}/" > {{ home_dir_path.stdout }}/cp-deployment/standalone/.keys

- name: Set openbao init data
  no_log: true
  set_fact:
    openbao_init_data: "{{ init_result.stdout | from_json }}"

- name: Unseal openbao
  no_log: true
  shell: |
    curl --silent --show-error -k -X POST -d '{"key": "{{ item }}"}' {{ openbao_url }}/v1/sys/unseal
  loop: "{{ openbao_init_data.keys_base64 }}"

- name: Enable approle auth method
  no_log: true
  shell: |
    curl --silent --show-error -k -H "X-Vault-Token: {{ openbao_init_data.root_token }}" -X POST -d '{"type": "approle"}' {{ openbao_url }}/v1/sys/auth/approle

- name: Enable kv secret engine
  no_log: true
  shell: |
    curl --silent --show-error -k -H "X-Vault-Token: {{ openbao_init_data.root_token }}" -X POST -d '{"type": "kv", "options": {"version": "2"}}' {{ openbao_url }}/v1/sys/mounts/secret

- name: Create service account for openbao
  shell: |
    kubectl delete serviceaccount openbao-controller -n kube-system
    kubectl delete clusterrolebinding openbao-controller -n kube-system
    kubectl create serviceaccount openbao-controller -n kube-system
    kubectl create clusterrolebinding openbao-controller --clusterrole=cluster-admin --serviceaccount=kube-system:openbao-controller -n kube-system
  ignore_errors: true

- name: Create token for openbao
  no_log: true
  shell: |
    kubectl create token openbao-controller --duration=999999h -n kube-system
  register: openbao_token

- name: Get cluster API URL
  shell: |
    kubectl config view --minify -o jsonpath='{.clusters[].cluster.server}'; echo
  register: cluster_api_url

- name: Store cluster infomation in openbao
  no_log: true  
  shell: |
    curl --silent --show-error -k -H "X-Vault-Token: {{ openbao_init_data.root_token }}" -X POST -d '{"data":{"clusterId": "cp-cluster", "clusterApiUrl": "{{ cluster_api_url.stdout }}", "clusterToken": "{{ openbao_token.stdout }}"}}' {{ openbao_url }}/v1/secret/data/cluster/cp-cluster

- name: Create openbao policy
  no_log: true  
  shell: |
    curl --silent --show-error -k -H "X-Vault-Token: {{ openbao_init_data.root_token }}" -X POST -d '{"policy":"path \"secret/*\" { capabilities = [\"create\", \"update\", \"delete\", \"read\"] } "}' {{ openbao_url }}/v1/sys/policy/cluster_policy

- name: Get pod CIDR
  shell: |
    kubectl get pods -n ingress-nginx --selector=app.kubernetes.io/name=ingress-nginx --field-selector=status.phase=Running -o jsonpath='{range .items[*]}{@.status.podIP}{"/16"}{"\t"}{end}'
  register: pod_cidr

- name: Create approle role
  no_log: true
  shell: |
    curl --silent --show-error -k -H "X-Vault-Token: {{ openbao_init_data.root_token }}" -X POST -d '{"secret_id_ttl": 0, "token_num_uses": 0, "token_ttl": "1m", "token_max_ttl": "10m", "token_explicit_max_ttl": "10m", "secret_id_num_uses": 0, "secret_id_bound_cidrs": ["127.0.0.6/16","{{ pod_cidr.stdout | trim }}"], "token_bound_cidrs": ["127.0.0.6/16","{{ pod_cidr.stdout | trim }}"], "token_policies": "cluster_policy"}' {{ openbao_url }}/v1/auth/approle/role/cluster_role

- name: Get approle role ID
  no_log: true
  shell: |
    curl --silent --show-error -k -H "X-Vault-Token: {{ openbao_init_data.root_token }}" -X GET {{ openbao_url }}/v1/auth/approle/role/cluster_role/role-id
  register: approle_role_id

- name: Get approle secret ID
  no_log: true
  shell: |
    curl --silent --show-error -k -H "X-Vault-Token: {{ openbao_init_data.root_token }}" -X POST {{ openbao_url }}/v1/auth/approle/role/cluster_role/secret-id
  register: approle_secret_id

- name: Set approle data
  no_log: true
  set_fact:
    openbao_approle_role_id: "{{ approle_role_id.stdout | from_json | json_query('data.role_id') }}"
    openbao_approle_secret_id: "{{ approle_secret_id.stdout | from_json | json_query('data.secret_id') }}"

- name: Create secret for controller manager
  no_log: true
  shell: |
    kubectl create secret generic controller-manager --from-literal=VAULT_ROLE_NAME=cluster_role --from-literal=VAULT_ROLE_ID={{ openbao_approle_role_id }} --from-literal=VAULT_SECRET_ID={{ openbao_approle_secret_id }} -n k-paas-system

- name: Derive secrets from ENV (fallback if role vars not provided)
  no_log: true
  set_fact:
    nhn_username_eff: "{{ nhn_username | default(lookup('env', 'NHN_USERNAME'), true) | trim }}"
    nhn_password_eff: "{{ nhn_password | default(lookup('env', 'NHN_PASSWORD'), true) | trim }}"
    nhn_tenant_id_eff: "{{ nhn_tenant_id | default(lookup('env', 'NHN_TENANT_ID'), true) | trim }}"
    nhn_vip_subnet_id_eff: "{{ nhn_vip_subnet_id | default(lookup('env', 'NHN_VIP_SUBNET_ID'), true) | trim }}"
  when:
    - lookup('env', 'CSP_TYPE') | trim == "NHN"

- name: Validate derived inputs
  no_log: true
  assert:
    that:
      - (nhn_username_eff | default('')) | length > 0
      - (nhn_password_eff | default('')) | length > 0
      - (nhn_tenant_id_eff | default('')) | length > 0
      - (nhn_vip_subnet_id_eff | default('')) | length > 0
    fail_msg: "Please check the NHN_USERNAME, NHN_PASSWORD, NHN_TENANT_ID, NHN_VIP_SUBNET_ID variable again."
  when:
    - lookup('env', 'CSP_TYPE') | trim == "NHN"

- name: Store NHN Cloud credentials in openbao
  no_log: true
  shell: |
    curl --silent --show-error -k -H "X-Vault-Token: {{ openbao_init_data.root_token }}" -X POST -d '{"data":{"NHN_TENANT_ID": "{{ nhn_tenant_id_eff }}", "NHN_USERNAME": "{{ nhn_username_eff }}", "NHN_PASSWORD": "{{ nhn_password_eff }}"}}' {{ openbao_url }}/v1/secret/data/csp/nhncloud
  when:
    - lookup('env', 'CSP_TYPE') | trim == "NHN"

- name: Build Configmap manifest
  no_log: true
  set_fact:
    configmap_manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nhncloud-config
        namespace: k-paas-system
      data:
        NHN_API_BASE_URL: "https://kr1-api-network-infrastructure.nhncloudservice.com"
        NHN_AUTH_URL: "https://api-identity-infrastructure.nhncloudservice.com/v2.0/tokens"
        NHN_VIP_SUBNET_ID: "{{ nhn_vip_subnet_id_eff }}"
  when:
    - lookup('env', 'CSP_TYPE') | trim == "NHN"

- name: Apply Configmap
  no_log: true
  shell: |
    kubectl apply -f -
  args:
    stdin: "{{ configmap_manifest | to_nice_yaml }}"
  when:
    - lookup('env','CSP_TYPE') | trim == 'NHN'

- name: Wipe sensitive vars
  no_log: true
  set_fact:
    openbao_init_data: null
    openbao_approle_role_id: null
    openbao_approle_secret_id: null

- name: Wipe sensitive vars
  no_log: true
  set_fact:
    nhn_username_eff: null
    nhn_password_eff: null
    nhn_tenant_id_eff: null
    nhn_vip_subnet_id_eff: null
    configmap_manifest: null
  when:
    - lookup('env', 'CSP_TYPE') | trim == "NHN"

- name: Create NHN Controller Resource
  shell: |
    kubectl apply -f {{ home_dir_path.stdout }}/cp-deployment/applications/controller/nhn-deploy.yaml
  when:
    - lookup('env', 'CSP_TYPE') | trim == "NHN"

- name: Unset NHN Cloud environment variables and clear from cp-cluster-vars.sh
  no_log: true
  shell: |
    unset NHN_USERNAME
    unset NHN_PASSWORD
    unset NHN_TENANT_ID
    unset NHN_VIP_SUBNET_ID

    sed -i "s/CSP_TYPE=.*/CSP_TYPE=/" {{ home_dir_path.stdout }}/cp-deployment/single/cp-cluster-vars.sh
    sed -i "s/NHN_USERNAME=.*/NHN_USERNAME=/" {{ home_dir_path.stdout }}/cp-deployment/single/cp-cluster-vars.sh
    sed -i "s/NHN_PASSWORD=.*/NHN_PASSWORD=/" {{ home_dir_path.stdout }}/cp-deployment/single/cp-cluster-vars.sh
    sed -i "s/NHN_TENANT_ID=.*/NHN_TENANT_ID=/" {{ home_dir_path.stdout }}/cp-deployment/single/cp-cluster-vars.sh
    sed -i "s/NHN_VIP_SUBNET_ID=.*/NHN_VIP_SUBNET_ID=/" {{ home_dir_path.stdout }}/cp-deployment/single/cp-cluster-vars.sh

    sed -i "s/CSP_TYPE=.*/CSP_TYPE=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh
    sed -i "s/NHN_USERNAME=.*/NHN_USERNAME=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh
    sed -i "s/NHN_PASSWORD=.*/NHN_PASSWORD=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh
    sed -i "s/NHN_TENANT_ID=.*/NHN_TENANT_ID=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh
    sed -i "s/NHN_VIP_SUBNET_ID=.*/NHN_VIP_SUBNET_ID=/" {{ home_dir_path.stdout }}/cp-deployment/multi/cp-cluster-vars.sh

    sed -i "s/CSP_TYPE=.*/CSP_TYPE=/" {{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars.sh
    sed -i "s/NHN_USERNAME=.*/NHN_USERNAME=/" {{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars.sh
    sed -i "s/NHN_PASSWORD=.*/NHN_PASSWORD=/" {{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars.sh
    sed -i "s/NHN_TENANT_ID=.*/NHN_TENANT_ID=/" {{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars.sh
    sed -i "s/NHN_VIP_SUBNET_ID=.*/NHN_VIP_SUBNET_ID=/" {{ home_dir_path.stdout }}/cp-deployment/standalone/cp-cluster-vars.sh
  when:
    - lookup('env', 'CSP_TYPE') | trim == "NHN"
