---
dependencies:
  - role: kubernetes/tokens
    when: kube_token_auth
    tags:
      - k8s-secrets
  - role: adduser
    user: "{{ addusers.etcd }}"
    when:
      - etcd_deployment_type == "kubeadm"
      - not (ansible_os_family in ["Flatcar", "Flatcar Container Linux by Kinvolk", "ClearLinux"] or is_fedora_coreos)
