---
dependencies:
  - role: kubernetes/kubeadm_common
  - role: adduser
    user: "{{ addusers.etcd }}"
    when:
      - etcd_deployment_type == "kubeadm"
      - not (ansible_os_family in ["Flatcar", "Flatcar Container Linux by Kinvolk", "ClearLinux"] or is_fedora_coreos)
  - role: network_plugin/calico_defaults
