---
- name: Crun | Download crun binary
  include_tasks: "../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.crun) }}"

- name: Copy crun binary from download dir
  copy:
    src: "{{ downloads.crun.dest }}"
    dest: "{{ bin_dir }}/crun"
    mode: 0755
    remote_src: true
