#################################################################################################################
# Create the pools that can be shared by multiple object stores. A single OSD is required
# in this example. This example shows two object stores being created with the same
# shared metadata and data pools. The pool sharing will utilize RADOS namespaces to keep the object store
# data independent, while avoiding the growth of PGs in the cluster.
#  kubectl create -f object-shared-pools.yaml
#  kubectl create -f object-a.yaml -f object-b.yaml
#################################################################################################################
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rgw-root
  namespace: rook-ceph # namespace:cluster
spec:
  name: .rgw.root
  failureDomain: host
  replicated:
    size: 1
    requireSafeReplicaSize: false
  parameters:
    pg_num: "8"
  application: rgw
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rgw-meta-pool
  namespace: rook-ceph # namespace:cluster
spec:
  failureDomain: host
  replicated:
    size: 1
    requireSafeReplicaSize: false
  parameters:
    pg_num: "8"
  application: rgw
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rgw-data-pool
  namespace: rook-ceph # namespace:cluster
spec:
  failureDomain: osd
  replicated:
    size: 1
    requireSafeReplicaSize: false
  application: rgw
