---
- name: Create nodes as docker containers
  hosts: localhost
  gather_facts: False
  roles:
    - { role: dind-host }

- name: Customize each node containers
  hosts: containers
  roles:
    - { role: dind-cluster }
