---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Download container platform deployment
  become: false
  git:
    repo: https://github.com/K-PaaS/cp-deploy.git
    dest: "{{ home_dir_path.stdout }}/cp-deployment/"
  ignore_errors: yes
