---
cert_manager_namespace: "cert-manager"
cert_manager_user: 1001
cert_manager_tolerations: []
cert_manager_affinity: {}
cert_manager_nodeselector: {}
cert_manager_dns_policy: "ClusterFirst"
cert_manager_dns_config: {}
cert_manager_controller_extra_args: []

## Allow http_proxy, https_proxy and no_proxy environment variables
## Details https://github.com/kubernetes-sigs/kubespray/blob/master/docs/proxy.md
cert_manager_http_proxy: "{{ http_proxy | default('') }}"
cert_manager_https_proxy: "{{ https_proxy | default('') }}"
cert_manager_no_proxy: "{{ no_proxy | default('') }}"

## Change leader election namespace when deploying on GKE Autopilot that forbid the changes on kube-system namespace.
## See https://github.com/jetstack/cert-manager/issues/3717
cert_manager_leader_election_namespace: kube-system
