---
pkgs_to_remove:
  systemd-timesyncd:
    - "{{ ntp_enabled }}"
    - "{{ ntp_package == 'ntp' }}"
    - "{{ ansible_os_family == 'Debian' }}"
pkgs:
  apparmor:
    - "{{ ansible_os_family == 'Debian' }}"
  apt-transport-https:
    - "{{ ansible_os_family == 'Debian' }}"
  aufs-tools:
    - "{{ ansible_os_family == 'Debian' }}"
    - "{{ ansible_distribution_major_version == '10' }}"
    - "{{ 'k8s_cluster' in group_names }}"
  bash-completion: []
  chrony:
    - "{{ ntp_enabled }}"
    - "{{ ntp_package == 'chrony' }}"
  conntrack:
    - "{{ ansible_os_family in ['Debian', 'RedHat'] }}"
    - "{{ ansible_distribution != 'openEuler' }}"
    - "{{ 'k8s_cluster' in group_names }}"
  conntrack-tools:
    - "{{ ansible_os_family == 'Suse' or ansible_distribution in ['Amazon', 'openEuler'] }}"
    - "{{ 'k8s_cluster' in group_names }}"
  container-selinux:
    - "{{ ansible_os_family == 'RedHat' }}"
    - "{{ 'k8s_cluster' in group_names }}"
  curl: []
  device-mapper:
    - "{{ ansible_os_family == 'Suse' or ansible_distribution == 'openEuler' }}"
    - "{{ 'k8s_cluster' in group_names }}"
  device-mapper-libs:
    - "{{ ansible_os_family == 'RedHat' }}"
    - "{{ ansible_distribution != 'openEuler' }}"
  e2fsprogs: []
  ebtables: []
  gnupg:
    - "{{ ansible_distribution == 'Debian' }}"
    - "{{ ansible_distribution_major_version in ['11', '12'] }}"
    - "{{ 'k8s_cluster' in group_names }}"
  iproute:
    - "{{ ansible_os_family == 'RedHat' }}"
  iproute2:
    - "{{ ansible_os_family != 'RedHat' }}"
  ipset:
    - "{{ kube_proxy_mode != 'ipvs' }}"
    - "{{ 'k8s_cluster' in group_names }}"
  iptables:
    - "{{ ansible_os_family in ['Debian', 'RedHat'] }}"
  iputils:
    - "{{ not ansible_os_family in ['Flatcar', 'Flatcar Container Linux by Kinvolk', 'Debian'] }}"
    - "{{ main_access_ip is defined }}"
    - "{{ ping_access_ip }}"
    - "{{ not is_fedora_coreos }}"
  iputils-ping:
    - "{{ ansible_os_family == 'Debian' }}"
    - "{{ main_access_ip is defined }}"
    - "{{ ping_access_ip }}"
  ipvsadm:
    - "{{ kube_proxy_mode == 'ipvs' }}"
    - "{{ 'k8s_cluster' in group_names }}"
  libseccomp:
    - "{{ ansible_os_family == 'RedHat' }}"
  libseccomp2:
    - "{{ ansible_os_family in ['Debian', 'Suse'] }}"
    - "{{ 'k8s_cluster' in group_names }}"
  libselinux-python:
    - "{{ ansible_distribution == 'Amazon' }}"
  libselinux-python3:
    - "{{ ansible_distribution == 'Fedora' }}"
  mergerfs:
    - "{{ ansible_distribution == 'Debian' }}"
    - "{{ ansible_distribution_major_version == '12' }}"
  nftables:
    - "{{ kube_proxy_mode == 'nftables' }}"
    - "{{ 'k8s_cluster' in group_names }}"
  nss:
    - "{{ ansible_os_family == 'RedHat' }}"
  ntp:
    - "{{ ntp_enabled }}"
    - "{{ ntp_package == 'ntp' }}"
  ntpsec:
    - "{{ ntp_enabled }}"
    - "{{ ntp_package == 'ntpsec' }}"
  openssl: []
  python-apt:
    - "{{ ansible_os_family == 'Debian' }}"
    - "{{ ansible_distribution_major_version == '10' }}"
  python3-apt:
    - "{{ ansible_os_family == 'Debian' }}"
    - "{{ ansible_distribution_major_version != '10' }}"
  python3-libselinux:
    - "{{ ansible_distribution in ['RedHat', 'CentOS'] }}"
  rsync: []
  socat: []
  software-properties-common:
    - "{{ ansible_os_family == 'Debian' }}"
  tar: []
  unzip: []
  xfsprogs: []
