---
cert_files:
  master:
  - "{{ etcd_cert_dir }}/member-{{ inventory_hostname }}.pem"
  - "{{ etcd_cert_dir }}/member-{{ inventory_hostname }}-key.pem"
  - "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}.pem"
  - "{{ etcd_cert_dir }}/admin-{{ inventory_hostname }}-key.pem"
  node:
  - "{{ etcd_cert_dir}}/node-{{ inventory_hostname }}.pem"
  - "{{ etcd_cert_dir}}/node-{{ inventory_hostname }}-key.pem"
