---
kube_owner: kube
kube_cert_group: kube-cert
etcd_data_dir: "/var/lib/etcd"

addusers:
  etcd:
    name: etcd
    comment: "Etcd user"
    create_home: no
    system: yes
    shell: /sbin/nologin
  kube:
    name: kube
    comment: "Kubernetes user"
    create_home: no
    system: yes
    shell: /sbin/nologin
    group: "{{ kube_cert_group }}"

adduser:
  name: "{{ user.name }}"
  group: "{{ user.name|default(None) }}"
  comment: "{{ user.comment|default(None) }}"
  shell: "{{ user.shell|default(None) }}"
  system: "{{ user.system|default(None) }}"
  create_home: "{{ user.create_home|default(None) }}"
