---
- name: Tear down heketi
  hosts: kube_control_plane[0]
  roles:
    - { role: tear-down }

- name: Teardown disks in heketi
  hosts: heketi-node
  become: yes
  roles:
    - { role: tear-down-disks }
