---
- name: "Reset | check if network device {{ iface }} is present"
  stat:
    path: "/sys/class/net/{{ iface }}"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: device_remains

- name: "Reset | remove network device {{ iface }}"
  command: "ip link del {{ iface }}"
  when: device_remains.stat.exists
