---
- name: Add list kubeconfig file name
  become: false
  shell: |
    ls {{ lookup('env', 'HOME') }}/.kube | grep -E '^config[0-9]+$'
  register: config_list

- name: Merge kubeconfig files
  become: false
  vars:
    kubeconfig_files: "{{ config_list.stdout_lines | map('regex_replace', '^(.*)$', lookup('env', 'HOME') + '/.kube/\\1') | list }}"
  shell: |
    export KUBECONFIG={{ kubeconfig_files | join(':') }}
    kubectl config view --merge --flatten > {{ lookup('env', 'HOME') }}/.kube/config
  with_items: "{{ kubeconfig_files }}"
