---
containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.2.4': "{{ containerd_package }}-1.2.4-3.1.el7"
  '1.2.5': "{{ containerd_package }}-1.2.5-3.1.el7"
  '1.2.6': "{{ containerd_package }}-1.2.6-3.3.el7"
  '1.2.10': "{{ containerd_package }}-1.2.10-3.2.el7"
  '1.2.12': "{{ containerd_package }}-1.2.12-3.1.el7"
  '1.2.13': "{{ containerd_package }}-1.2.13-3.2.el7"
  '1.3.7': "{{ containerd_package }}-1.3.7-3.1.el{{ ansible_distribution_major_version }}"
  '1.3.9': "{{ containerd_package }}-1.3.9-3.1.el{{ ansible_distribution_major_version }}"
  'stable': "{{ containerd_package }}-1.3.9-3.1.el{{ ansible_distribution_major_version }}"
  'edge': "{{ containerd_package }}-1.3.9-3.1.el{{ ansible_distribution_major_version }}"
