apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-validation-test-web-server-conf
  labels:
    app: multus-validation-test-web-server
data:
  server.conf: |
    server {
        # listen on all IPv4 addrs
        listen       8080;
        # listen on all IPv6 addrs
        listen       [::]:8080;
        server_name  localhost;

        # return the client ip upon connect
        location / {
            default_type text/plain;
            return 200 "$remote_addr\n";
        }
    }
