---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Download Terraform
  shell: |
    wget https://releases.hashicorp.com/terraform/1.3.4/terraform_1.3.4_linux_amd64.zip
    unzip terraform_1.3.4_linux_amd64.zip

- name: Copy Terraform
  copy:
    src: "{{ home_dir_path.stdout }}/terraform"
    dest: "/usr/bin/terraform"
    mode: 0755

- name: Delete Terraform
  file:
    path: "{{ home_dir_path.stdout }}/terraform"
    state: absent


- name: Delete Terraform Zip
  file:
    path: "{{ home_dir_path.stdout }}/terraform_1.3.4_linux_amd64.zip"
    state: absent
