---
- name: Reset | check vxlan.calico network device
  stat:
    path: /sys/class/net/vxlan.calico
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: vxlan

- name: Reset | remove the network vxlan.calico device created by calico
  command: ip link del vxlan.calico
  when: vxlan.stat.exists

- name: Reset | check dummy0 network device
  stat:
    path: /sys/class/net/dummy0
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: dummy0

- name: Reset | remove the network device created by calico
  command: ip link del dummy0
  when: dummy0.stat.exists

- name: Reset | get and remove remaining routes set by bird
  shell: set -o pipefail && ip route show proto bird | xargs -i bash -c "ip route del {} proto bird "
  args:
    executable: /bin/bash
  changed_when: false
