---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
  # Use this with the example `groupsnapshotclass.yaml`.
  # Not needed if the volume group snapshots are not required.
  labels:
    group: snapshot-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
