---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-block-rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
