---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: copy keadm token file
  copy:
    src: "{{ home_dir_path.stdout }}/keadm_token"
    dest: "{{ home_dir_path.stdout }}"

- name: get keadm token
  shell: "echo $(<{{ home_dir_path.stdout }}/keadm_token)"
  register: keadm_token
  args:
    executable: /bin/bash

- name: keadm join
  shell: "nohup keadm join --cloudcore-ipport={{ cloudcore_vip }}:30000 --token={{ keadm_token.stdout }} --kubeedge-version 1.12.0"

- name: remove keadm token file
  file:
    path: "{{ home_dir_path.stdout }}/keadm_token"
    state: absent

- name: modify edgecore
  lineinfile:
    path: /etc/kubeedge/config/edgecore.yaml
    insertafter: "tailoredKubeletConfig:"
    line: "{{ items }}"
  with_items:
    - "      clusterDomain: cluster.local"
    - "        - {{ cloudcore_vip }}"
    - "      clusterDNS:"
