---
- name: get home dir path
  become_user: ubuntu
  shell: "echo $HOME"
  register: home_dir_path

- name: copy keadm token file
  copy:
    src: "{{ home_dir_path.stdout }}/keadm_token"
    dest: "{{ home_dir_path.stdout }}"

- name: get keadm token
  shell: "echo $(<{{ home_dir_path.stdout }}/keadm_token)"
  register: keadm_token
  args:
    executable: /bin/bash

- name: keadm join
  shell: "nohup keadm join --cloudcore-ipport={{ master_node_public_ip }}:10000 --token={{ keadm_token.stdout }} --cgroupdriver systemd --remote-runtime-endpoint unix:///var/run/crio/crio.sock --runtimetype remote --kubeedge-version 1.10.0"

- name: remove keadm token file
  file:
    path: "{{ home_dir_path.stdout }}/keadm_token"
    state: absent
