---
- name: get home dir path
  become_user: ubuntu
  shell: "echo $HOME"
  register: home_dir_path

- name: copy keadm (amd64)
  copy:
    src: "{{ home_dir_path.stdout }}/paas-ta-container-platform-deployment/edge/keadm/amd64/keadm"
    dest: "/usr/bin/keadm"
    mode: 0755
