---
- name: Remove swapfile from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

# kubelet fails even if ansible_swaptotal_mb = 0
- name: Check swap
  command: /sbin/swapon -s
  register: swapon
  changed_when: no

- name: Disable swap
  command: /sbin/swapoff -a
  when:
    - swapon.stdout
  ignore_errors: "{{ ansible_check_mode }}"  # noqa ignore-errors

- name: Disable swapOnZram for Fedora
  command: touch /etc/systemd/zram-generator.conf
  when:
    - swapon.stdout
    - ansible_distribution in ['Fedora']
  ignore_errors: "{{ ansible_check_mode }}"  # noqa ignore-errors
