---
- name: remove-node | Delete node
  command: "{{ kubectl }} delete node {{ kube_override_hostname|default(inventory_hostname) }}"
  delegate_to: "{{ groups['kube_control_plane']|first }}"
  when:
    - groups['kube_control_plane'] | length > 0
    # ignore servers that are not nodes
    - inventory_hostname in groups['k8s_cluster'] and kube_override_hostname|default(inventory_hostname) in nodes.stdout_lines
  retries: "{{ delete_node_retries }}"
  # Sometimes the api-server can have a short window of indisponibility when we delete a master node
  delay: "{{ delete_node_delay_seconds }}"
  register: result
  until: result is not failed
