- type: replace
  path: /instance_groups/name=master/networks/-
  value:
    name: vip
    type: vip
    static_ips: [((caas_master_public_url))]
- type: replace
  path: /instance_groups/name=master/networks/0/default?
  value: [dns, gateway]

- type: replace
  path: /variables/name=tls-kubernetes/options/common_name
  value: ((caas_master_public_url))
- type: replace
  path: /variables/name=tls-kubernetes/options/alternative_names/-
  value: ((caas_master_public_url))
