---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: change kube-proxy config
  shell: |
    kubectl patch daemonset kube-proxy -n kube-system --patch-file {{ home_dir_path.stdout }}/cp-deployment/edge/ha-cloudcore/kube-proxy.yaml
    kubectl patch daemonset calico-node -n kube-system --patch-file {{ home_dir_path.stdout }}/cp-deployment/edge/ha-cloudcore/kube-proxy.yaml
    kubectl patch daemonset speaker -n metallb-system --patch-file {{ home_dir_path.stdout }}/cp-deployment/edge/ha-cloudcore/kube-proxy.yaml

- name: add cloudcore node label
  shell: |
    kubectl label nodes {{ cloudcore1_node_hostname }} cloudcore=enable
    kubectl label nodes {{ cloudcore2_node_hostname }} cloudcore=enable
  ignore_errors: true

- name: deploy ha cloudcore
  shell: |
    kubectl apply -f {{ home_dir_path.stdout }}/cp-deployment/edge/ha-cloudcore/01-ha-prepare.yaml
    kubectl apply -f {{ home_dir_path.stdout }}/cp-deployment/edge/ha-cloudcore/02-ha-configmap.yaml
    kubectl apply -f {{ home_dir_path.stdout }}/cp-deployment/edge/ha-cloudcore/03-ha-deployment.yaml

- name: Pause keadm init
  pause:
    minutes: 1

- name: create keadm token file
  shell: keadm gettoken > keadm_token

- name: deploy kubeedge crd
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/router/router_v1_ruleEndpoint.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/router/router_v1_rule.yaml

- name: add cloudcore svc external ip
  shell: |
    cat << EOF | kubectl apply -f -
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: cloudcore
      namespace: metallb-system
    spec:
      addresses:
      - {{ cloudcore_private_vip }}/32
      autoAssign: false
    EOF

    kubectl rollout restart daemonset speaker -n metallb-system
