---
- name: Warn for usage of deprecated role
  fail:
    msg: remove-node/pre-remove is deprecated, switch to remove_node/pre_remove
  ignore_errors: true # noqa ignore-errors
  run_once: true

- name: Compat for direct role import
  import_role:
    name: remove_node/pre_remove
