---
- name: Get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: Deploy ingress nginx controller
  shell: kubectl apply -f {{ home_dir_path.stdout }}/cp-deployment/applications/ingress-nginx-1.11.3/deploy.yaml
