---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: deploy Ingress Nginx Controller
  shell: |
    kubectl apply -f {{ home_dir_path.stdout }}/paas-ta-container-platform-deployment/standalone/applications/ingress-nginx-1.4.0/deploy.yaml
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
