---
- name: Kube-router | Add annotations on kube_control_plane
  command: "{{ kubectl }} annotate --overwrite node {{ ansible_hostname }} {{ item }}"
  with_items:
  - "{{ kube_router_annotations_master }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when: kube_router_annotations_master is defined and 'kube_control_plane' in group_names

- name: Kube-router | Add annotations on kube_node
  command: "{{ kubectl }} annotate --overwrite node {{ ansible_hostname }} {{ item }}"
  with_items:
  - "{{ kube_router_annotations_node }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when: kube_router_annotations_node is defined and 'kube_node' in group_names

- name: Kube-router | Add common annotations on all servers
  command: "{{ kubectl }} annotate --overwrite node {{ ansible_hostname }} {{ item }}"
  with_items:
  - "{{ kube_router_annotations_all }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when: kube_router_annotations_all is defined and 'k8s_cluster' in group_names
