---
- name: Kubelet | reload systemd
  systemd_service:
    daemon_reload: true
  listen: Node | restart kubelet

- name: Kubelet | restart kubelet
  service:
    name: kubelet
    state: restarted
  listen: Node | restart kubelet
