- type: replace
  path: /instance_groups/name=haproxy/networks/name=((service_private_networks_name))
  value:
    name: ((service_private_nat_networks_name))
    default: [dns, gateway]

- type: replace
  path: /instance_groups/name=haproxy/networks/name=((service_public_networks_name))
  value:
    name: ((service_public_networks_name))
    static_ips: ((haproxy_public_url))
