---
- name: get home dir path
  become: false
  shell: "echo $HOME"
  register: home_dir_path

- name: cri-o download
  shell: |
    wget https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.30.0.tar.gz
    tar zxvf cri-o.amd64.v1.30.0.tar.gz
    cd cri-o
    ./install
  args:
    executable: /bin/bash
  when: ansible_architecture == "x86_64"

- name: cri-o download
  shell: |
    wget https://storage.googleapis.com/cri-o/artifacts/cri-o.arm64.v1.30.0.tar.gz
    tar zxvf cri-o.arm64.v1.30.0.tar.gz
    cd cri-o
    ./install
  args:
    executable: /bin/bash
  when: ansible_architecture == "aarch64"

- name: remove cri-o tar file
  file:
    path: "{{ home_dir_path.stdout }}/cri-o.amd64.v1.30.0.tar.gz"
    state: absent
  when: ansible_architecture == "x86_64"

- name: remove cri-o tar file
  file:
    path: "{{ home_dir_path.stdout }}/cri-o.arm64.v1.30.0.tar.gz"
    state: absent
  when: ansible_architecture == "aarch64"

- name: remove cri-o dir
  file:
    path: "{{ home_dir_path.stdout }}/cri-o"
    state: absent

- name: enable crio.service
  shell: |
    echo unqualified-search-registries = [\"docker.io\", \"quay.io\"] > /etc/containers/registries.conf
    systemctl daemon-reload
    systemctl enable crio.service
    systemctl start crio.service
  ignore_errors: true
