---
- name: Restart and enable cri-dockerd
  command: /bin/true
  notify:
    - Cri-dockerd | reload systemd
    - Cri-dockerd | restart docker.service
    - Cri-dockerd | reload cri-dockerd.socket
    - Cri-dockerd | reload cri-dockerd.service
    - Cri-dockerd | enable cri-dockerd service

- name: Cri-dockerd | reload systemd
  systemd:
    name: cri-dockerd
    daemon_reload: true
    masked: no

- name: Cri-dockerd | restart docker.service
  service:
    name: docker.service
    state: restarted

- name: Cri-dockerd | reload cri-dockerd.socket
  service:
    name: cri-dockerd.socket
    state: restarted

- name: Cri-dockerd | reload cri-dockerd.service
  service:
    name: cri-dockerd.service
    state: restarted

- name: Cri-dockerd | enable cri-dockerd service
  service:
    name: cri-dockerd.service
    enabled: yes
