apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgemesh-agent
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]