apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-agent-cfg
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
data:
  edgemesh-agent.yaml: |
    apiVersion: agent.edgemesh.config.kubeedge.io/v1alpha1
    kind: EdgeMeshAgent
    commonConfig:
      dummyDeviceName: edgemesh0
      dummyDeviceIP: 169.254.96.16
      configMapName: edgemesh-agent-cfg
    goChassisConfig:
      protocol:
        tcpBufferSize: 8192
        tcpClientTimeout: 5
        tcpReconnectTimes: 3
      loadBalancer:
        defaultLBStrategy: RoundRobin
        supportLBStrategies:
          - RoundRobin
          - Random
          - ConsistentHash
        consistentHash:
          partitionCount: 100
          replicationFactor: 10
          load: 1.25
    modules:
      edgeDNS:
        listenPort: 53
      edgeProxy:
        enable: true
        listenPort: 40001
      edgeGateway:
        enable: false
        nic: "*"
        includeIP: "*"
        excludeIP: "*"
      tunnel:
        enable: true
        listenPort: 20006
