---
- name: Download helm apt key
  shell: curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null

- name: Install apt-transport-https package
  apt:
    name: apt-transport-https

- name: Add helm apt repo
  shell: echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

- name: Install helm
  apt:
    name: helm=3.17.4-1
    update_cache: yes
