#!/bin/bash

export MASTER_NODE_HOSTNAME=
export MASTER_NODE_PUBLIC_IP=
export MASTER_NODE_PRIVATE_IP=
export WORKER1_NODE_HOSTNAME=
export WORKER1_NODE_PRIVATE_IP=
export WORKER2_NODE_HOSTNAME=
export WORKER2_NODE_PRIVATE_IP=
export WORKER3_NODE_HOSTNAME=
export WORKER3_NODE_PRIVATE_IP=
export CALICO_MTU=1450
