---
- name: install mosquitto
  shell: |
    apt-get install -y mosquitto

- name: modify mosquitto config
  shell: |
    echo "\nallow_anonymous true\nbind_address 0.0.0.0" >> /etc/mosquitto/mosquitto.conf
    systemctl restart mosquitto.service

- name: modify edgecore
  shell: |
    sed -i '153s/false/true/g' /etc/kubeedge/config/edgecore.yaml

- name: restart edgecore
  shell: |
    systemctl daemon-reload
    systemctl restart edgecore.service
