---
- name: install mosquitto
  shell: |
    apt-get install -y mosquitto

- name: modify edgecore
  shell: |
    sed -i '153s/false/true/g' /etc/kubeedge/config/edgecore.yaml

- name: restart edgecore
  shell: |
    systemctl daemon-reload
    systemctl restart edgecore.service
