---
- name: Download kubectl binary
  shell: curl -LO "https://dl.k8s.io/release/v1.27.5/bin/linux/amd64/kubectl"

- name: Install kubectl
  shell: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Remove kubectl file
  file:
    path: "kubectl"
    state: absent
