---
- name: Check if kubectl is installed
  shell: |
    command -v kubectl
  register: kubectl_installed
  changed_when: false
  failed_when: false

- name: Download kubectl binary for specified Kubernetes version
  get_url:
    url: "https://dl.k8s.io/release/v1.33.5/bin/linux/amd64/kubectl"
    dest: "/tmp/kubectl"
    mode: "0755"
  when: kubectl_installed.stdout == ""

- name: Install kubectl binary to /usr/local/bin
  copy:
    src: "/tmp/kubectl"
    dest: "/usr/local/bin/kubectl"
    owner: root
    group: root
    mode: "0755"
    remote_src: yes
  when: kubectl_installed.stdout == ""

- name: Remove temporary kubectl binary
  file:
    path: "/tmp/kubectl"
    state: absent
  when: kubectl_installed.stdout == ""
